apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-database
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-database
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-db
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-discord
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-discord
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-discord
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-email
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-email
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-email
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-oauth
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-oauth
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-oauth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-session
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-session
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-session
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-storage
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-storage
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-storage
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-vatusa
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-vatusa
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-vatusa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-webhooks
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-webhooks
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-webhooks
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-auth-jwks
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-auth-jwks
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-auth-jwks
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-auth-vatsim
  namespace: zan-dev
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: secret-auth-vatsim
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: zan-dev-auth-vatsim
