apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- external-secrets/external-secrets.yaml
images:
- name: adhp/zan-frontend
  newName: adhp/frontend
  newTag: zan-main-c8540b1
- name: denartcc/api
  newName: adhp/api
  newTag: dev-a596810
#- api/merge/deployment.yaml
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
