apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- external-secrets/external-secrets.yaml
images:
- name: adhp/zan-frontend
  newName: adhp/frontend
  newTag: zan-main-9bbe726
- name: denartcc/api
  newName: adhp/api
  newTag: dev-5a65049
#- api/merge/deployment.yaml
patches:
- path: api/merge/certificate.yaml
- path: api/merge/ingress.yaml
- path: frontend/merge/certificate.yaml
- path: frontend/merge/ingress.yaml
