apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-zanartcc-org-tls
spec:
  dnsNames:
  - api.zanartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-zanartcc-org-tls
