apiVersion: v1
data:
  config.yaml: |
    server:
      port: 3000
      host: 127.0.0.1
    database:
      host: {{.DB_HOST | default "mysql.mysql.svc.cluster.local"}}
      port: 25060
      user: {{.DB_USER | default "root"}}
      password: {{.DB_PASSWORD | default "root"}}
      database: {{.DB_DATABASE | default "zan"}}
      ca_cert: {{.DB_CA_CERT | default ""}}
      automigrate: true
    discord:
      webhooks:
        pending_feedback: {{.DISCORD_WEBHOOK_PENDING_FEEDBACK}}
        broadcast_feedback: {{.DISCORD_WEBHOOK_BROADCAST_FEEDBACK}}
        uploads: {{.DISCORD_WEBHOOK_UPLOADS}}
        role: {{.DISCORD_WEBHOOK_ROLE}}
        visiting_application: {{.DISCORD_WEBHOOK_VISITING_APPLICATION}}
        seniorstaff: {{.DISCORD_WEBHOOK_SENIORSTAFF}}
        online: {{.DISCORD_WEBHOOK_ONLINE}}
        default: {{.DISCORD_WEBHOOK_DEFAULT}}
      client_id: {{.DISCORD_CLIENT_ID}}
      client_secret: {{.DISCORD_CLIENT_SECRET}}
    email:
      host: {{.EMAIL_HOST | default "localhost"}}
      port: {{.EMAIL_PORT | default "25"}}
      user: {{.EMAIL_USER | default "root"}}
      password: {{.EMAIL_PASSWORD | default "root"}}
      from: {{.EMAIL_FROM | default "root@localhost"}}
      template_dir: "/app/templates"
    facility:
      activity:
        enabled: false
        min_hours: 2
        period: 2
        run_on_day: 1
        run_at_hour: 0
        run_at_minute: 0
      feedback:
        discord_webhook_name: "feedback"
      frontend_url: {{.FRONTEND_URL | default "https://www.vzanartcc.net" }}
      training_requests:
        enabled: true
        positions:
        - Delivery
        - Ground
        - Local
        - Approach
        - Center
        - Oceanic
      visiting:
        discord_webhook_name: "visitor"
        rating_min: S1
        send_welcome: true
        send_removal: true
        send_rejected: true
      stats:
        enabled: true
        discord_broadcast: true
        discord_broadcast_webhook_name: "online"
        prefixes:
        - ANC
        - FAI
        - FBK
        - EIL
        - EDF
        - BET
        - ENA
        - AKN
        - MRI
        - ADQ
        - JNU
        - ZAN
      training_requests:
        enabled: true
        discord:
          training_staff: "training_staff"
          scheduled: "training_scheduled"
          show_all_scheduled: true
        positions:
        - Ground
        - Local
        - Major Local
        - Approach
        - Major Approach
        - Enroute
        - Oceanic
        max_requests_per_user: 1
    session:
      cookie:
        name: "{{.SESSION_NAME | default "zan_session"}}"
        key: "{{.SESSION_KEY | default "zan_session"}}"
        max_age: 604800
        domain: "{{.SESSION_DOMAIN | default ".denartcc.org"}}"
        path: "/"
    storage:
      base_url: {{.STORAGE_BASE_URL | default "https://cdn.vzanartcc.net" }}
      access_key: {{.STORAGE_ACCESS_KEY | default "12345"}}
      secret_key: {{.STORAGE_SECRET_KEY | default "12345"}}
      bucket: {{.STORAGE_BUCKET | default "denartcc"}}
      region: {{.STORAGE_REGION | default "us-east-1"}}
      endpoint: {{.STORAGE_ENDPOINT | default ""}}
    oauth:
      base_URL: "https://auth.vzanartcc.net"
      endpoints:
        token: "/oauth/token"
        user: "/v1/info"
        authorize: "/oauth/authorize"
      client_id: "{{.OAUTH_CLIENT_ID | default "zan"}}"
      client_secret: "{{.OAUTH_CLIENT_SECRET | default "zan"}}"
      my_base_URL: "{{.OAUTH_MY_BASE_URL | default "https://api.dev.vzanartcc.net" }}"
    vatusa:
      facility: "ZAN"
      api_key: "{{.VATUSA_API_KEY | default "zan"}}"
    metrics:
      enabled: true
      port: 8080
      path: /metrics
kind: ConfigMap
metadata:
  name: api-config
