apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bot
  name: bot
  namespace: zdv
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - env:
        - name: BOT_CONFIG
          valueFrom:
            secretKeyRef:
              key: bot-config
              name: bot-secrets
        image: denartcc/bot:main
        imagePullPolicy: Always
        name: bot
        resources:
          limits:
            cpu: 400m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
