apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-denartcc-org-tls
spec:
  dnsNames:
  - www.denartcc.org
  - denartcc.org
  - new.denartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-denartcc-org-tls