apiVersion: v1
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientID
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: adh-partnership
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - 'CiliumIdentity'
      clusters:
        - "*"
  url: https://argo.ca.adhp.dev
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: config
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd