apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: cloudflare-token
    remoteRef:
      key: cloudflare_token