ingress-nginx:
  controller:
    kind: DaemonSet
    config:
      proxy-body-size: 128m
    service:
      externalTrafficPolicy: Local
      ipFamilyPolicy: RequireDualStack
      ipFamilies:
      - IPv4
      - IPv6
