mysql:
  auth:
    username: zdv
    database: zdv
    existingSecret: passwords
  primary:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1024Mi
        cpu: 250m