apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-vzanartcc-net-tls
spec:
  dnsNames:
  - www.vzanartcc.net
  - vzanartcc.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-vzanartcc-net-tls