apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/service.yaml
- discord/ingress.yaml
- ids/certificate.yaml
- ids/deployment.yaml
- ids/ingress.yaml
- ids/poddistruptionpolicy.yaml
- ids/service.yaml
- logging/logging.yaml
- logging/flow.yaml
- logging/output.yaml
- logging/cronjob-cleanup.yaml
- chart-parser/cronjob.yaml
- auth/poddistruptionpolicy.yaml
- discord/poddistruptionpolicy.yaml
- external-secrets/external-secrets.yaml
images:
- name: adhp/zan-frontend
  newName: adhp/frontend
  newTag: zan-v1.7.1696687928.40-5f05b4b
- name: adhp/zan-ids
  newName: adhp/zan-ids
  newTag: main-fef557b
- name: denartcc/api
  newName: adhp/api
  newTag: main-0547f47
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: df0fe4b
