apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ids-zanartcc-org
spec:
  dnsNames:
  - ids.zanartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-ids-zanartcc-org
