apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-zanartcc.org
spec:
  dnsNames:
  - auth.zanartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-auth-zanartcc-org
