apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: configs
resources:
- base/argocd-cm.yaml
- base/argocd-ingress.yaml
- base/argocd-rbac-cm.yaml
- base/cert-manager-ClusterIssuer.yaml
- base/logging.yaml