apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-denartcc-org-tls
spec:
  dnsNames:
  - api.vzanartcc.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-denartcc-org-tls