apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hawton-cloud
spec:
  dnsNames:
  - hawton.cloud
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-hawton-cloud
